[package]
name = "OpenFaaSRPC"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.46"
serde = "1.0.197"
serde_json = "1.0.79"
