---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.linkerd.io/skip-inbound-ports: '4222'
    config.linkerd.io/skip-outbound-ports: '4222'
    linkerd.io/inject: enabled
  labels:
    access: openfaas-system
    istio-injection: enabled
    role: openfaas-system
  name: openfaas2
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.linkerd.io/skip-inbound-ports: '4222'
    config.linkerd.io/skip-outbound-ports: '4222'
    linkerd.io/inject: enabled
  labels:
    istio-injection: enabled
    role: openfaas-fn
  name: openfaas2-fn
